[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
next_rs = { path = ".." }
serde_json = "^1.0.107"
tokio = { version = "^1.33.0", features = ["macros", "rt-multi-thread"] }
